// <auto-generated />
namespace RadexRent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedenumonCompany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedenumonCompany));
        
        string IMigrationMetadata.Id
        {
            get { return "201804101753581_Added enum on Company"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
